### ISSUE TITLE
无法找到文件apps.json

### ISSUE THREAD

**Issue by xiaobai008** [aeverj/weblive#3]
出现以下新问题：
2020/12/30 10:50:39 无法找到文件apps.json
panic: 无法找到文件apps.json

goroutine 1 [running]:
log.Panic(0xc00010fdd0, 0x1, 0x1)
	/usr/lib/go-1.13/src/log/log.go:338 +0xac
github.com/x/x/pkg/wappalyzer.Init(0xc000086eb8)
	/root/weblive/pkg/wappalyzer/getFinger.go:211 +0x545
main.main()
	/root/weblive/webinfo.go:46 +0x37
![image](https://user-images.githubusercontent.com/47384653/103364988-07519a80-4afa-11eb-89d6-34ce0e48511a.png)

**Comment by aeverj** [comment]
需要两个文件，如下图
![图片](https://user-images.githubusercontent.com/37864882/103412797-daf95500-4bb1-11eb-96b0-43d6ec19ee46.png)

**Comment by xiaobai008** [comment]
感谢解答，确认此方法可以解决问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aeverj/weblive"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月31日(星期四) 晚上9:48
收件人:&nbsp;"aeverj/weblive"<weblive@noreply.github.com&gt;;
抄送:&nbsp;"455338606"<455338606@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [aeverj/weblive] 无法找到文件apps.json (#3)



 需要两个文件，如下图

**Comment by xiaobai008** [comment]
感谢解答，确认此方法可以解决此问题。
