### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by Lizhiyao1** [aeverj/weblive#4]
环境：Go version go1.17.5 windows/amd64
**运行时出现以下错误，查阅资料无法解决**：

`panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x90 pc=0x11a0e30]

goroutine 45097 [running]:
regexp.(*Regexp).doExecute(0xc0000d56c0, {0x0, 0x0}, {0xc000451760, 0xc000559c70, 0xfdafb0}, {0x0, 0x115cf01}, 0x12c1ee0, 0x0, ...)
        E:/GoLang/src/regexp/exec.go:527 +0x90
regexp.(*Regexp).doMatch(...)
        E:/GoLang/src/regexp/exec.go:514
regexp.(*Regexp).Match(...)
        E:/GoLang/src/regexp/regexp.go:531
github.com/x/x/pkg/wappalyzer.hasapp(0xc0007def50, 0xc0009ec060)
        E:/tools/webinfo/weblive/pkg/wappalyzer/getFinger.go:195 +0x7fc
github.com/x/x/pkg/wappalyzer.(*wappalyzer).Analyze(0xc00022a6f0, 0xc0007def50)
        E:/tools/webinfo/weblive/pkg/wappalyzer/getFinger.go:247 +0xa7
main.main.func3({0xc000012378, 0x0})
        E:/tools/webinfo/weblive/webinfo.go:110 +0x174
created by main.main
        E:/tools/webinfo/weblive/webinfo.go:103 +0x65d`

**Comment by aeverj** [comment]
> 环境：Go version go1.17.5 windows/amd64 **运行时出现以下错误，查阅资料无法解决**：
> 
> `panic: runtime error: invalid memory address or nil pointer dereference [signal 0xc0000005 code=0x0 addr=0x90 pc=0x11a0e30]
> 
> goroutine 45097 [running]: regexp.(*Regexp).doExecute(0xc0000d56c0, {0x0, 0x0}, {0xc000451760, 0xc000559c70, 0xfdafb0}, {0x0, 0x115cf01}, 0x12c1ee0, 0x0, ...) E:/GoLang/src/regexp/exec.go:527 +0x90 regexp.(*Regexp).doMatch(...) E:/GoLang/src/regexp/exec.go:514 regexp.(*Regexp).Match(...) E:/GoLang/src/regexp/regexp.go:531 github.com/x/x/pkg/wappalyzer.hasapp(0xc0007def50, 0xc0009ec060) E:/tools/webinfo/weblive/pkg/wappalyzer/getFinger.go:195 +0x7fc github.com/x/x/pkg/wappalyzer.(*wappalyzer).Analyze(0xc00022a6f0, 0xc0007def50) E:/tools/webinfo/weblive/pkg/wappalyzer/getFinger.go:247 +0xa7 main.main.func3({0xc000012378, 0x0}) E:/tools/webinfo/weblive/webinfo.go:110 +0x174 created by main.main E:/tools/webinfo/weblive/webinfo.go:103 +0x65d`

问题出现在getFinger.go:195
好像是正则匹配的时候出的问题
正则是在app.json中保存的，可能是app.json内容有问题，重新下载app.json试试

**Comment by Lizhiyao1** [comment]
> > 环境：Go version go1.17.5 windows/amd64 **运行时出现以下错误，查阅资料无法解决**：
> > `panic: runtime error: invalid memory address or nil pointer dereference [signal 0xc0000005 code=0x0 addr=0x90 pc=0x11a0e30]
> > goroutine 45097 [running]: regexp.(*Regexp).doExecute(0xc0000d56c0, {0x0, 0x0}, {0xc000451760, 0xc000559c70, 0xfdafb0}, {0x0, 0x115cf01}, 0x12c1ee0, 0x0, ...) E:/GoLang/src/regexp/exec.go:527 +0x90 regexp.(*Regexp).doMatch(...) E:/GoLang/src/regexp/exec.go:514 regexp.(*Regexp).Match(...) E:/GoLang/src/regexp/regexp.go:531 github.com/x/x/pkg/wappalyzer.hasapp(0xc0007def50, 0xc0009ec060) E:/tools/webinfo/weblive/pkg/wappalyzer/getFinger.go:195 +0x7fc github.com/x/x/pkg/wappalyzer.(*wappalyzer).Analyze(0xc00022a6f0, 0xc0007def50) E:/tools/webinfo/weblive/pkg/wappalyzer/getFinger.go:247 +0xa7 main.main.func3({0xc000012378, 0x0}) E:/tools/webinfo/weblive/webinfo.go:110 +0x174 created by main.main E:/tools/webinfo/weblive/webinfo.go:103 +0x65d`
> 
> 问题出现在getFinger.go:195 好像是正则匹配的时候出的问题 正则是在app.json中保存的，可能是app.json内容有问题，重新下载app.json试试

已解决，非常感谢
